// Generated by scripts/sync-github.mjs. Do not edit by hand: run `npm run sync:github`.
import type { Repo } from "@/lib/types";

export const githubUser = "MihrimatriX";

/** Profile photo, sized for the largest avatar. */
export const githubAvatar = "https://avatars.githubusercontent.com/u/28717150?v=4&s=400";

export const repos: Repo[] = [
  {
    "name": "ps5-showcase",
    "description": "Projelerimi bir oyun konsolunun ana ekranı gibi sergileyen portfolyo. Next.js + TypeScript, iki dilli (TR/EN). Klavye, fare, dokunmatik ekran ve oyun kumandasıyla gezilir. Hiçbir ses, logo veya ikon dosyası yok: sesler Web Audio ile tarayıcıda sentezleniyor, kapak görselleri her projenin renk paletinden SVG olarak üretiliyor.",
    "url": "https://github.com/MihrimatriX/ps5-showcase",
    "language": "HTML",
    "stars": 3,
    "topics": [
      "portfolio",
      "portfolio-project",
      "portfolio-website",
      "ps5"
    ],
    "pushedAt": "2026-10-02T11:31:07Z"
  },
  {
    "name": "photon-engine",
    "description": "PhotonEngine is a modern C++20 rendering engine built for photorealistic image synthesis. It implements physically-based light transport algorithms with a focus on material accuracy, performance, and extensibility.",
    "url": "https://github.com/MihrimatriX/photon-engine",
    "language": "C++",
    "stars": 1,
    "topics": [
      "cpp",
      "engine",
      "path-tracing",
      "pbr",
      "render",
      "renderer"
    ],
    "pushedAt": "2026-10-06T09:24:49Z"
  },
  {
    "name": "bookmark-editor-save",
    "description": "A powerful Chrome extension for managing, organizing, importing, and exporting bookmarks with advanced search, duplicate detection, and statistics.",
    "url": "https://github.com/MihrimatriX/bookmark-editor-save",
    "language": "JavaScript",
    "stars": 1,
    "topics": [
      "bookmark-export",
      "bookmark-organizer",
      "bookmark-tools",
      "browser-extension",
      "chrome-plugin"
    ],
    "pushedAt": "2026-10-02T06:20:47Z"
  },
  {
    "name": "arr-stack",
    "description": "Production-ready Docker stack for automated media management. Includes TV/movie/music/book managers,  torrent client, media servers, and unified dashboard. One-command deployment.",
    "url": "https://github.com/MihrimatriX/arr-stack",
    "language": "Python",
    "stars": 1,
    "topics": [
      "arr",
      "arrstack",
      "bazarr",
      "homarr",
      "homelab",
      "jellyfin",
      "lidarr",
      "plex",
      "prowlarr",
      "sonarr"
    ],
    "pushedAt": "2026-09-30T18:00:12Z"
  },
  {
    "name": "online-tas-kagit-makas",
    "description": "Gerçek zamanlı, eleme usulü taş-kağıt-makas turnuva uygulaması.  React + Node.js + Socket.io",
    "url": "https://github.com/MihrimatriX/online-tas-kagit-makas",
    "homepage": "https://tkm.ahmetfuzunkaya.com",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "socket-io",
      "tmk"
    ],
    "pushedAt": "2026-10-06T09:39:18Z"
  },
  {
    "name": "element-api",
    "description": "Polyglot mikroservis platformu — periyodik tablo element ticareti, dağıtık saga, API gateway ve tam observability stack.",
    "url": "https://github.com/MihrimatriX/element-api",
    "homepage": "https://element-api.ahmetfuzunkaya.com/",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "api",
      "docker",
      "elk-stack",
      "grafana",
      "microservices"
    ],
    "pushedAt": "2026-10-05T22:30:28Z"
  },
  {
    "name": "dialoq",
    "description": "Kullanıcılar mesleğe göre filtreleyerek anında eşleşir, 10 saniyelik karşılıklı onay sonrası 45 saniyelik sesli görüşme yapar ve isterlerse arkadaş ekleyebilir. Ayrıca çok kişili ses odalarına katılabilir veya kendi odalarını açabilirler.",
    "url": "https://github.com/MihrimatriX/dialoq",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "matching",
      "matching-engine",
      "websocket",
      "websocket-api",
      "websocket-application",
      "websocket-chat",
      "websockets-server"
    ],
    "pushedAt": "2026-10-05T20:42:30Z"
  },
  {
    "name": "projects",
    "description": "Windows odaklı 40 bağımsız masaüstü ve web uygulaması koleksiyonu. Her proje kendi klasöründe, kendi README.md dosyası ve çoğunlukla run.ps1 ile tek tıkla çalıştırılabilir.",
    "url": "https://github.com/MihrimatriX/projects",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "csharp",
      "flutter",
      "python",
      "script",
      "typescript",
      "windows"
    ],
    "pushedAt": "2026-10-05T20:32:06Z"
  },
  {
    "name": "win8-metro",
    "description": "Projelerimi Windows 8.1 tarzı bir Metro Başlangıç ekranında sergileyen portfolyo. Next.js + TypeScript, iki dilli (TR/EN). Masaüstü ve tablette Windows 8.1, telefonda Windows Phone 8.1 düzeni açılır. Hiçbir sistem logosu, yazı tipi dosyası ya da sesi yok: ikonlar özgün SVG, sesler Web Audio ile tarayıcıda sentezleniyor, görseller her projenin renk ",
    "url": "https://github.com/MihrimatriX/win8-metro",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "metro-ui",
      "windows-8"
    ],
    "pushedAt": "2026-10-05T11:37:16Z"
  },
  {
    "name": "xp-clone-react",
    "description": "Tarayıcıda çalışan bir Windows XP (Luna) masaüstü. Açılış ekranıyla başlar, Hoş Geldiniz ekranından oturum açılır. Masaüstündeki pencereler sürüklenir, boyutlandırılır, simge durumuna küçültülür ve ekranı kaplar. Uygulamalar gerçekten çalışır ve tarayıcıda saklanan ortak bir dosya sistemini kullanır.",
    "url": "https://github.com/MihrimatriX/xp-clone-react",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "react",
      "windows-xp",
      "windows-xp-ui"
    ],
    "pushedAt": "2026-10-05T11:36:52Z"
  },
  {
    "name": "macos-clone-react",
    "description": "A desktop in the browser that recreates macOS Tahoe and its Liquid Glass look. You can drag and resize windows, launch apps from the Dock, move files around in Finder and run commands in Terminal. Files, notes and settings are saved in the browser, so a reload doesn't wipe them.",
    "url": "https://github.com/MihrimatriX/macos-clone-react",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "macos",
      "macos-app",
      "macos-tahoe",
      "react",
      "react-components"
    ],
    "pushedAt": "2026-10-05T07:37:34Z"
  },
  {
    "name": "ubuntu-react",
    "description": "Ubuntu 24.04 LTS masaüstünün (GNOME 46, Yaru, Ubuntu Dock) tarayıcıda çalışan bir kopyası. Her uygulama gerçekten çalışır ve hepsi aynı sanal dosya sistemini paylaşır: Terminal'de oluşturduğun dosya Files'ta anında görünür, orada çift tıklayınca Text Editor'de açılır, kaydedince cat yeni içeriği gösterir.",
    "url": "https://github.com/MihrimatriX/ubuntu-react",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "react",
      "react-ubuntu",
      "ubuntu",
      "ubuntu-clone",
      "ubuntu-ui"
    ],
    "pushedAt": "2026-10-05T07:37:34Z"
  },
  {
    "name": "iphone-clone-react",
    "description": "An iPhone that runs in your browser. An iPhone 15 Pro Max sits on a desk rendered with Three.js; its screen is a React UI in the iOS 26 \"Liquid Glass\" style with 16 working apps.",
    "url": "https://github.com/MihrimatriX/iphone-clone-react",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "ios",
      "ios-ui",
      "react",
      "react-fiber",
      "treejs"
    ],
    "pushedAt": "2026-10-05T07:36:48Z"
  },
  {
    "name": "android-react",
    "description": "Tarayıcıda çalışan bir Android telefonu. Görünüşü ve hareketleri Android 15'e olabildiğince yakın, içindeki uygulamalar da gerçekten çalışıyor. İki sekme açıp birbirinizi arayabilir, mesajlaşabilir, bilgisayarınızın kamerasıyla fotoğraf çekip galeride görebilirsiniz.",
    "url": "https://github.com/MihrimatriX/android-react",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "android",
      "android-ui",
      "react",
      "zustand",
      "zustand-state-management"
    ],
    "pushedAt": "2026-10-04T19:54:58Z"
  },
  {
    "name": "afu-coming-soon",
    "description": "A modern \"coming soon\" page built with Next.js and React 19, adorned with retro CRT TV screen effects and glitch animations.",
    "url": "https://github.com/MihrimatriX/afu-coming-soon",
    "homepage": "https://ahmetfuzunkaya.com",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "custom-cursor",
      "glitch-animation",
      "modern-ui"
    ],
    "pushedAt": "2026-10-04T13:47:54Z"
  },
  {
    "name": "backend-dotnet",
    "description": "Modern, ölçeklenebilir ve güvenli bir e-ticaret backend API'si - .NET 9, JWT kimlik doğrulama, Redis önbellekleme, PostgreSQL veritabanı, Prometheus/Grafana izleme ve Docker desteği ile üretim için hazır.",
    "url": "https://github.com/MihrimatriX/backend-dotnet",
    "language": "C#",
    "stars": 0,
    "topics": [
      "api",
      "e-commerce",
      "microservice",
      "rest",
      "restfull"
    ],
    "pushedAt": "2026-10-02T11:54:27Z"
  },
  {
    "name": "backend-spring",
    "description": "Bu proje, modern e-ticaret platformları için tasarlanmış, ölçeklenebilir ve güvenli bir backend API'sidir. JWT tabanlı kimlik doğrulama, Redis önbellekleme, PostgreSQL veritabanı, Prometheus ve Grafana ile izleme ve Docker desteği ile donatılmıştır.",
    "url": "https://github.com/MihrimatriX/backend-spring",
    "language": "Java",
    "stars": 0,
    "topics": [
      "api",
      "e-commerce",
      "grafana",
      "microservices",
      "rest",
      "spring-boot"
    ],
    "pushedAt": "2026-10-02T11:50:50Z"
  },
  {
    "name": "temp-shop-net",
    "description": "Temp Shop Net, localhost:5000’de çalışan bir ASP.NET (.NET) API’ye bağlanan ve ürün/sepet/checkout akışlarını tüketen bir e‑ticaret web uygulaması projesidir.",
    "url": "https://github.com/MihrimatriX/temp-shop-net",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "aspnet-core",
      "dotnet",
      "fullstack",
      "rest-api",
      "shopping-cart"
    ],
    "pushedAt": "2026-10-02T10:30:42Z"
  },
  {
    "name": "demo-social-media-api",
    "description": "Modern, katmanlı bir .NET 9 sosyal medya API örneği. Kimlik doğrulama, arkadaşlık, gönderi/yorum/beğeni/kayıt, dosya yükleme (MinIO) ve gerçek zamanlı sohbet (SignalR) özellikleri içerir. Geliştirilebilir, test edilebilir ve buluta hazır olacak şekilde Domain-Driven ve CQRS + MediatR desenleriyle yapılandırılmıştır.",
    "url": "https://github.com/MihrimatriX/demo-social-media-api",
    "language": "C#",
    "stars": 0,
    "topics": [
      "cqrs",
      "ddd",
      "mediatr",
      "wep-api"
    ],
    "pushedAt": "2026-10-01T22:42:48Z"
  },
  {
    "name": "Temp-Shop",
    "description": "Next.js 15, TypeScript ve Tailwind CSS ile geliştirilmiş, çoklu backend desteği (Mock, .NET Core, Spring Boot) sunan, modern ve ölçeklenebilir e-ticaret platformu.",
    "url": "https://github.com/MihrimatriX/Temp-Shop",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "axios",
      "ecommerce",
      "modern-ui",
      "radix-ui",
      "react-hook-form",
      "shadcn-ui",
      "tailwind",
      "zod",
      "zustand"
    ],
    "pushedAt": "2026-10-01T22:07:44Z"
  },
  {
    "name": "react-shop",
    "description": "Kimlik doğrulama (JWT), sepet, sipariş, ödeme ve hesap uçları sunucu tarafında express ile sağlanır; ön yüz bu API’ye /api üzerinden (geliştirmede Vite proxy ile) erişir. Ürün listeleme, arama, kategori, kampanya.",
    "url": "https://github.com/MihrimatriX/react-shop",
    "homepage": "https://react-shop.ahmetfuzunkaya.com",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "ecommerce",
      "tanstack-query",
      "zustand"
    ],
    "pushedAt": "2026-10-01T22:06:49Z"
  },
  {
    "name": "react-os-win",
    "description": "Tarayıcıda çalışan, Windows 11 masaüstünü uçtan uca simüle eden tam ekran web uygulaması. MSI BIOS POST ekranından başlayarak kilit ekranı, masaüstü, pencere yönetimi, görev çubuğu ve onlarca yerleşik uygulama sunar.",
    "url": "https://github.com/MihrimatriX/react-os-win",
    "homepage": "https://win11-react.ahmetfuzunkaya.com/",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "react",
      "react-ui",
      "win11",
      "windows-react"
    ],
    "pushedAt": "2026-10-01T18:45:11Z"
  },
  {
    "name": "react-spider-solitaire",
    "description": "A modern, production-ready Spider Solitaire game built with React, TypeScript, Vite, and Tailwind CSS.",
    "url": "https://github.com/MihrimatriX/react-spider-solitaire",
    "homepage": "https://spider-solitaire.ahmetfuzunkaya.com",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "react",
      "solitaire",
      "solitaire-card-game",
      "vite"
    ],
    "pushedAt": "2026-10-01T17:21:50Z"
  },
  {
    "name": "easy-pomodoro",
    "description": "Pomodoro, görevler, alışkanlıklar ve istatistikler — hesap açmadan, tamamen cihazında.",
    "url": "https://github.com/MihrimatriX/easy-pomodoro",
    "homepage": "https://easy-pomodoro.ahmetfuzunkaya.com",
    "language": "Dart",
    "stars": 0,
    "topics": [
      "flutter",
      "mobil",
      "pomodoro",
      "web"
    ],
    "pushedAt": "2026-10-01T14:26:03Z"
  },
  {
    "name": "ytdlp-gui",
    "description": "YouTube (ytdlp-gui) Downloader: Easily download channels, playlists, and videos, with automatic cookie support for member. See README for details.",
    "url": "https://github.com/MihrimatriX/ytdlp-gui",
    "language": "Python",
    "stars": 0,
    "topics": [
      "cookies",
      "ytdlp",
      "ytdlp-cookies",
      "ytdlp-deskop",
      "ytdlp-gui"
    ],
    "pushedAt": "2026-10-01T12:21:56Z"
  },
  {
    "name": "film-review-movie",
    "description": "TMDB-powered movie and TV discovery app built with Next.js 16, TypeScript, and Tailwind CSS, featuring multilingual UI, blog pages, and a lightweight admin panel.",
    "url": "https://github.com/MihrimatriX/film-review-movie",
    "homepage": "https://filmrev-movie.ahmetfuzunkaya.com",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "app-router",
      "film-review",
      "movie-app",
      "multilingual",
      "nextjs",
      "tmdb",
      "tv-series"
    ],
    "pushedAt": "2026-10-01T11:54:21Z"
  },
  {
    "name": "react-rick-and-morty",
    "description": "Basic react project with rick and morty api. ",
    "url": "https://github.com/MihrimatriX/react-rick-and-morty",
    "homepage": "https://rick-morty.ahmetfuzunkaya.com",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "api",
      "react",
      "rest",
      "rick-and-morty",
      "rickandmortyapi"
    ],
    "pushedAt": "2026-10-01T10:59:39Z"
  },
  {
    "name": "video-compression-analyzer",
    "description": "Video Compression Analyzer is a fully client-side web application that analyzes your video files and provides optimal compression settings",
    "url": "https://github.com/MihrimatriX/video-compression-analyzer",
    "homepage": "https://vid-report.ahmetfuzunkaya.com/",
    "language": "TypeScript",
    "stars": 0,
    "topics": [
      "analyzes",
      "compression",
      "ffmpeg",
      "ffmpeg-wasm"
    ],
    "pushedAt": "2026-09-30T18:08:49Z"
  },
  {
    "name": "awesome-web-components",
    "description": "React component library of canvas and Three.js visual effects, with a Vite showcase app. Scoped styles, embeddable and responsive.",
    "url": "https://github.com/MihrimatriX/awesome-web-components",
    "homepage": "https://aw-component.ahmetfuzunkaya.com",
    "language": "JavaScript",
    "stars": 0,
    "topics": [
      "canvas",
      "component-library",
      "threejs",
      "visual-effects"
    ],
    "pushedAt": "2026-09-30T13:28:56Z"
  }
];
