// Pulls public GitHub repositories into content/github.ts for the recruiter's profile.
// No token needed for public repos (60 requests/hour); set GITHUB_TOKEN in .env.local to lift that. Run: npm run sync:github
import { writeFileSync } from "node:fs";

try {
  process.loadEnvFile(".env.local");
} catch {}

const USER = "MihrimatriX";
/** Repos that aren't projects: the profile README. */
const SKIP = new Set([USER]);

const headers = { Accept: "application/vnd.github+json", ...(process.env.GITHUB_TOKEN && { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }) };
const res = await fetch(`https://api.github.com/users/${USER}/repos?per_page=100&type=owner`, { headers });
if (!res.ok) throw new Error(`GitHub: ${res.status} ${await res.text()}`);
const user = await fetch(`https://api.github.com/users/${USER}`, { headers }).then((r) => r.json());

const repos = (await res.json())
  .filter((r) => !r.fork && !r.archived && !SKIP.has(r.name))
  // Most starred first, then most recently worked on.
  .sort((a, b) => b.stargazers_count - a.stargazers_count || b.pushed_at.localeCompare(a.pushed_at))
  .map((r) => ({
    name: r.name,
    description: r.description ?? "",
    url: r.html_url,
    // Some homepages are stored without a scheme.
    homepage: r.homepage ? (/^https?:\/\//.test(r.homepage) ? r.homepage : `https://${r.homepage}`) : undefined,
    language: r.language ?? undefined,
    stars: r.stargazers_count,
    topics: r.topics ?? [],
    pushedAt: r.pushed_at,
  }));

writeFileSync(
  "content/github.ts",
  `// Generated by scripts/sync-github.mjs. Do not edit by hand: run \`npm run sync:github\`.\nimport type { Repo } from "@/lib/types";\n\nexport const githubUser = ${JSON.stringify(USER)};\n\n/** Profile photo, sized for the largest avatar. */\nexport const githubAvatar = ${JSON.stringify(user.avatar_url ? `${user.avatar_url}&s=400` : undefined)};\n\nexport const repos: Repo[] = ${JSON.stringify(repos, null, 2)};\n`,
);
console.log(`Wrote ${repos.length} repos to content/github.ts`);
