// Pulls real PS5 games from IGDB into content/games.ts.
// Needs Twitch app credentials in .env.local (CLIENT_ID, CLIENT_SECRET from dev.twitch.tv/console), then: npm run sync:games
// The IGDB access and the game mapping live in lib/igdb.ts, shared with the store's live search.
import { writeFileSync } from "node:fs";
import { FIELDS, PS5, igdb, searchTerm, toProject } from "../lib/igdb.ts";

try {
  process.loadEnvFile(".env.local");
} catch {}
if (!process.env.CLIENT_ID || !process.env.CLIENT_SECRET) {
  console.error("CLIENT_ID / CLIENT_SECRET missing: add them to .env.local");
  process.exit(1);
}

/** Games the visitor already owns: the home screen, in order. Titles are matched against IGDB's PS5 catalog. */
const TITLES = [
  "Marvel's Spider-Man 2",
  "God of War Ragnarök",
  "Astro Bot",
  "Ghost of Tsushima",
  "Horizon Forbidden West",
  "Elden Ring",
  "Ratchet & Clank: Rift Apart",
  "Returnal",
  "Gran Turismo 7",
  "Final Fantasy VII Rebirth",
];

const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

const found = [];
for (const title of TITLES) {
  // Searching one title at a time stays well under IGDB's 4 requests/second.
  const hits = await igdb("games", `fields ${FIELDS}; search "${searchTerm(title)}"; where platforms = (${PS5}) & version_parent = null; limit 10;`);
  const g = hits.find((x) => norm(x.name) === norm(title)) ?? hits[0];
  if (g) found.push(g);
  else console.warn(`not found on PS5: ${title}`);
}
if (!found.length) throw new Error("No games found");
const ownedCount = found.length;

// The store: the best-rated PS5 games the visitor doesn't own yet, then the most anticipated upcoming ones.
const now = Math.floor(Date.now() / 1000);
const base = `fields ${FIELDS}; where platforms = (${PS5}) & version_parent = null & game_type = 0 & cover != null`;
const store = [
  ...(await igdb("games", `${base} & total_rating_count > 80; sort total_rating desc; limit 24;`)),
  ...(await igdb("games", `${base} & first_release_date > ${now}; sort hypes desc; limit 8;`)),
];
for (const g of store) if (!found.some((f) => f.id === g.id)) found.push(g);

const games = found.map((g, i) => toProject(g, i, i < ownedCount));

writeFileSync(
  "content/games.ts",
  `// Generated by scripts/sync-igdb.mjs from IGDB. Do not edit by hand: run \`npm run sync:games\`.\nimport type { Project } from "@/lib/types";\n\nexport const games: Project[] = ${JSON.stringify(games, null, 2)};\n`,
);
console.log(`Wrote ${games.length} games to content/games.ts (${ownedCount} owned, ${games.length - ownedCount} in the store)`);
